#!/bin/bash

mkdir ~/EnacPack_temp
cd ~/EnacPack_temp

#Installing Chrome
curl -L -o "https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg" 
hdiutil mount -nobrowse googlechrome.dmg 
cp -R "/Volumes/Google Chrome/Google Chrome.app" /Applications
hdiutil unmount "/Volumes/Google Chrome" 
rm googlechrome.dmg

#Installing EnacDrive
curl -L -o ENACdrives - 1.0 .6.dmg "http://enacdrives.epfl.ch/releases/download?os=macosx" 
hdiutil mount -nobrowse ENACdrives-1.0 .6.dmg
cp -R "/Volumes/ENACdrives/ENACdrives.app" /Applications 
hdiutil unmount "/Volumes/ENACdrives/" 
rm ENACdrives-1.0 .6.dmg

