#!/bin/bash

mkdir ~/EnacPack_temp
cd ~/EnacPack_temp

#Installing Dropbox
curl -L -o Dropbox.dmg "https://www.dropbox.com/download?plat=mac&type=full"
hdiutil mount -nobrowse Dropbox.dmg 
cp -R "/Volumes/Dropbox Installer/Dropbox.app" /Applications
hdiutil unmount "/Volumes/Dropbox Installer" 
rm Dropbox.dmg

#Installing EnacDrive
curl -L -o ENACdrives - 1.0 .6.dmg "http://enacdrives.epfl.ch/releases/download?os=macosx" 
hdiutil mount -nobrowse ENACdrives-1.0 .6.dmg
cp -R "/Volumes/ENACdrives/ENACdrives.app" /Applications 
hdiutil unmount "/Volumes/ENACdrives/" 
rm ENACdrives-1.0 .6.dmg

