#!/bin/bash

mkdir ~/EnacPack_temp
cd ~/EnacPack_temp

#Installing Dropbox
curl -L -o Dropbox.dmg "https://www.dropbox.com/download?plat=mac&type=full"
hdiutil mount -nobrowse Dropbox.dmg 
cp -R "/Volumes/Dropbox Installer/Dropbox.app" /Applications
hdiutil unmount "/Volumes/Dropbox Installer" 
rm Dropbox.dmg

#Installing Carbon Copy Clone
curl -L -o ccc.zip "https://bombich.com/software/download_ccc.php" -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36" 
unzip ccc.zip 
mv "Carbon Copy Cloner.app" /Applications 
rm ccc.zip

