#!/bin/bash

mkdir ~/EnacPack_temp
cd ~/EnacPack_temp

#Installing Google Drive
curl -L -o "https://dl-ssl.google.com/drive/installgoogledrive.dmg" 
hdiutil mount -nobrowse installgoogledrive.dmg 
cp -R "/Volumes/Install Google Drive/Google Drive.app" /Applications
hdiutil unmount "/Volumes/Install Google Drive" 
rm installgoogledrive.dmg

#Installing Carbon Copy Clone
curl -L -o ccc.zip "https://bombich.com/software/download_ccc.php" -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36" 
unzip ccc.zip 
mv "Carbon Copy Cloner.app" /Applications 
rm ccc.zip

